version: "3.8"
services:

  frontend:
    build: ./frontend
    image: raj/frontend
    container_name: application
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 1

  backend:
    build: ./backend
    image: raj/backend
    container_name: backend
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    deploy:
      replicas: 1

  service1:
    build: ./service1
    image: raj/service1
    container_name: service1
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
      replicas: 1

  service2:
    build: ./service2
    image: raj/service2
    container_name: service2
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    deploy:
      replicas: 1

  nginx:
    build: ./nginx
    container_name: nginx
    enviroment:
      - SERVER_NAME=20.124.246.104
    restart: always
    network_mode: host
    


