version: "3.7"
services:

  frontend:
    build: ./frontend
    image: rajdockerac/frontend
    container_name: application
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 1

  backend:
    build: ./backend
    image: rajdockerac/backend
    container_name: backend
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    deploy:
      replicas: 1

  service1:
    build: ./service1
    image: rajdockerac/service1
    container_name: service1
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
      replicas: 1

  service2:
    build: ./service2
    image: rajdockerac/service2
    container_name: service2
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    deploy:
      replicas: 1

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: .nginx/nginx.conf
      target: /rtc/nginx/nginx.conf
    restart: always
    
    


